### PR TITLE
Allowing full emailID as username too #13

### PR DESCRIPTION
**Pull request by skbly7**
Refer discussion on #13

### CODE REVIEW

**Comment by mrinaldhar** [comment]
This breaks login.

**Comment by skbly7** [comment]
Breaks as in?

For which test case. :confused:

**Comment by mrinaldhar** [comment]
It's not working for me here. :P 
Try: https://osdg.iiit.ac.in/staging/CabShare/

**Comment by skbly7** [comment]
Holy! :disappointed: 

I wrote wrong variable.. :cry: 
Really sorry for it. Updated the pull request.

**Comment by mrinaldhar** [comment]
Doing it this way means that mrinal.dhar@gmail.com would also work for login, if my LDAP is mrinal.dhar
 
Do we care about that?

**Comment by skbly7** [comment]
I think we shouldn't as per our use case. Though it can be decision from you and @amoghbl1 side. If needed can add check for IIIT only domains.

**Comment by mrinaldhar** [comment]
Hmm. We won't be shifting to open, non-LDAP based email, at least in the distant future. So I think its alright. Merging.

**Pull request merged**
