### PR TITLE
Fix #1 - Show only future public trips

### LINKED ISSUE #1: Display publicTrips only if travel date is in the future.

### PR DESCRIPTION
**Pull request by pinkeshbadjatiya**
Fix for #1 
Considering only date is better rather than using exact time.

### CODE REVIEW

**Comment by mrinaldhar** [comment]
Would doing this at the backend make more sense?

**Comment by pinkeshbadjatiya** [comment]
agreed.
Should i do it?

**Comment by mrinaldhar** [comment]
Sure, go for it! :)

**Comment by pinkeshbadjatiya** [comment]
If we do it in backend, then there would be no way to see all the trips.
Is there any possibility of adding a button to see all trips? and default would be just to dispplay future trips.

**Comment by mrinaldhar** [comment]
Do we really need to see all public trips that happened in the past? 
In the right sidebar for individual users, they can see *their* previous trips, which makes sense. 

But listing them all on the "All public trips" page would just clutter it unnecessarily, IMO. What use case would require a user to want to see those?

**Comment by pinkeshbadjatiya** [comment]
Actually there is not need for it. Just an idea. :)
Fixing it in backend then.

**Comment by mrinaldhar** [comment]
This looks good. :+1: 

Can you also add a restriction on the UI for the datepicker, so that a user cannot select a date in the past when creating a trip?

**Comment by pinkeshbadjatiya** [comment]
sure

**Comment by pinkeshbadjatiya** [comment]
done :)

**Pull request merged**
